language: node_js
node_js:
  - 10.12.0
script:
  - cd utils
  - npm i
  - npm run build
  - npm run lint
  - cd ../client
  - npm i ../utils
  - npm i
  - npm run build
  - npm run lint
  - cd ../core
  - npm i ../utils
  - npm i
  - npm run build
  - npm run lint
  - npm run coverage
  - cd ..

# before_deploy:
#   - echo "" > .gitignore

# deploy:
#   provider: npm
#   email: NPM_EMAIL
#   api_key: NPM_KEY
#   skip_cleanup: true
#   on:
#     tags: true
#     branch: master
